### ISSUE TITLE
[ERROR] Unknown option: ansi

### ISSUE THREAD

**Issue by tommy-muehle** [phar-io/composer-plugin#4]
The problem is that the Composer binary which comes via Homebrew always add "--ansi" or "--no-ansi" to all commands. But in this special case for us, the parameters are in the wrong order. See [here](https://github.com/Homebrew/homebrew-php/blob/master/Formula/composer.rb#L33).

**Comment by eclipxe13** [comment]
Please, release a new version with this commit.

Errors building on travis-ci using version `^0.1.0`: `[ERROR] Unknown option: ansi`
https://travis-ci.org/phpcfdi/cfditopdf/jobs/357267221#L572

Changing required version to `master-dev` solves the issue

**Comment by tommy-muehle** [comment]
@belanur, @theseer 
Can you please do this? I've currently no rights to do this.

**Comment by sebastianheuer** [comment]
Done!

**Comment by MacDada** [comment]
Hi, I have a problem with ansi param:

Jenkins console output:

```
+ bin/composer.phar phive:run install
Phive 0.12.1 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]   Unknown command 'install--ansi'
```

Calling it from Ant:

```
<target name="phive-install" depends="composer-download">
	<exec executable="${basedir}/bin/composer.phar" failonerror="true">
		<arg value="phive:run" />
		<arg value="install" />
	</exec>
</target>

$ ant phive-install
Unable to locate tools.jar. Expected to find it in /usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar
Buildfile: /vagrant/build.xml
composer-download:
phive-install:
     [exec] Phive 0.12.1 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
     [exec] 
     [exec] [ERROR]   Unknown command 'install--ansi'
```

Finally as  Composer hook:

```
"scripts": {
	"post-root-package-install": [
		"SymfonyStandard\\Composer::hookRootPackageInstall"
	],
	"post-install-cmd": [
		"@composer phive:run install"
	],
}

$ bin/composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update

Generating autoload files
muglug/package-versions-56:  Generating version class...
muglug/package-versions-56: ...done generating version class
Phive 0.12.1 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]   Unknown command 'install--ansi'
```

Calling it "by hand" works:

```
$  bin/composer.phar phive:run install
Phive 0.12.1 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Copying phpcs-3.4.0.phar to ./tools/phpcs
Linking /home/vagrant/.phive/phars/psalm.phar to ./tools/psalm
```

**Comment by MacDada** [comment]
I got it working with Ant, by using `--no-ansi` option. But I don't think I should have to use it.

	<target name="phive-install" depends="composer-download">
		<exec executable="${basedir}/bin/composer.phar" failonerror="true">
			<arg value="--no-ansi" />
			<arg value="phive:run" />
			<arg value="install" />
		</exec>
	</target>
