### ISSUE TITLE
Detect the bin-dir from Composer as target directory

### ISSUE THREAD

**Issue by tommy-muehle** [phar-io/composer-plugin#5]
Maybe we should use the [bin-dir](https://getcomposer.org/doc/06-config.md#bin-dir) from Composer by default as the target directory for installed phar's. 

What are you think @theseer, @belanur? I would it prefer.

**Comment by theseer** [comment]
I think that's _not_ a good idea, because:
- It would differ from phive's standalone behavior
- Installed "binaries" can conflict with composer dependencies, leading to unexpected side effects
